version: '3'

services:
  my-pypi:
    image: my-pypi
    container_name: my-pypi
    hostname: my-pypi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./auth
        target: /data/auth
      - type: volume
        source: pypi-server
        target: /data/packages
    ports:
      - 8080:8080
    command: -P /data/auth/.htpasswd -a update /data/packages
    restart: always

volumes:
  pypi-server: